import type { ScanReport } from "./types";

export const demoReport: ScanReport = {
  mode: "demo",
  scanned: 128,
  health: 78,
  fixed: 4,
  pending: 3,
  scannedAt: "2026-07-29T04:20:00.000Z",
  risks: [
    {
      urn: "urn:li:dataset:(example,analytics.customer_orders,PROD)",
      name: "analytics.customer_orders",
      domain: "Commerce",
      health: 61,
      risk: 82,
      severity: "high",
      impact: "3 downstream dashboards",
      reason: "Missing owner on a highly-used dataset",
      status: "needs_review",
      citation: { id: "CIT-demo-001", source: "lineage", fact: "3 downstream assets depend on this entity", confidence: 0.84 },
    },
    {
      urn: "urn:li:dataset:(example,analytics.order_events,PROD)",
      name: "analytics.order_events",
      domain: "Commerce",
      health: 69,
      risk: 64,
      severity: "medium",
      impact: "1 dbt model, 2 reports",
      reason: "Description does not cover recent schema fields",
      status: "proposed",
      citation: { id: "CIT-demo-002", source: "schema", fact: "2 fields have no descriptions", confidence: 0.91 },
    },
    {
      urn: "urn:li:dataset:(example,analytics.products,PROD)",
      name: "analytics.products",
      domain: "Catalog",
      health: 84,
      risk: 38,
      severity: "low",
      impact: "1 dashboard",
      reason: "Governance tag has not been reviewed recently",
      status: "needs_review",
      citation: { id: "CIT-demo-003", source: "freshness", fact: "Governance metadata is 45 days old", confidence: 0.76 },
    },
    {
      urn: "urn:li:dataset:(example,analytics.customer_profiles,PROD)",
      name: "analytics.customer_profiles",
      domain: "Customer",
      health: 73,
      risk: 57,
      severity: "medium",
      impact: "2 ML features",
      reason: "Ownership is present but lacks a backup owner",
      status: "verified",
      citation: { id: "CIT-demo-004", source: "ownership", fact: "Primary owner exists; no secondary owner", confidence: 0.88 },
    },
  ],
};
